name: Analyze Database

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run analysis
        run: |
          python analyze_all_data.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: analysis-images
          path: analysis_output
